apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-api
  labels:
    app: synergychat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api
  template:
    metadata:
      labels:
        app: synergychat-api
    spec:
      automountServiceAccountToken: false
      containers:
      - name: synergychat-api
        image: bootdotdev/synergychat-api:latest
        env:
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: synergychat-api-configmap
                key: API_PORT
          - name: API_DB_FILEPATH
            valueFrom:
              configMapKeyRef:
                name: synergychat-api-configmap
                key: API_DB_FILEPATH
          - name: CRAWLER_BASE_URL
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_BASE_URL
                name: synergychat-api-configmap
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "512Mi"
        volumeMounts:
        - name: synergychat-api-volume
          mountPath: /persist
      volumes:
      - name: synergychat-api-volume
        persistentVolumeClaim:
          claimName: synergychat-api-pvc